#!/usr/bin/env bash
set -euo pipefail

MASTER_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
: "${AVATAR_S3_BUCKET:?AVATAR_S3_BUCKET is required}"
: "${AVATAR_SQS_QUEUE_URL:?AVATAR_SQS_QUEUE_URL is required}"
: "${AVATAR_DYNAMODB_JOBS_TABLE:?AVATAR_DYNAMODB_JOBS_TABLE is required}"
: "${AVATAR_DYNAMODB_RUNNERS_TABLE:?AVATAR_DYNAMODB_RUNNERS_TABLE is required}"
: "${AVATAR_DYNAMODB_ENROLLMENTS_TABLE:?AVATAR_DYNAMODB_ENROLLMENTS_TABLE is required}"
: "${AVATAR_DYNAMODB_IDEMPOTENCY_TABLE:?AVATAR_DYNAMODB_IDEMPOTENCY_TABLE is required}"

export AVATAR_INFRA_MODE=aws
export AVATAR_MASTER_ENABLED=1
export AVATAR_LOCAL_BENCHMARKS=0
cd "$MASTER_ROOT"
exec node dist/main.js
